import { Product, Platform, ProductPrice } from '@/context/ShopContext';

// Helper functions to generate realistic data
const generateId = (index: number): string => {
  return (index + 1).toString();
};

const generatePrices = (basePrice: number, productId: number): ProductPrice[] => {
  // Add slight variations in pricing across platforms (±15%)
  // Also add occasional stock unavailability (about 10% chance)
  return [
    { 
      platform: 'blinkit' as Platform, 
      price: Math.round(basePrice * (0.95 + Math.random() * 0.2)), 
      available: Math.random() > 0.1, 
      deliveryTime: '10 mins' 
    },
    { 
      platform: 'zepto' as Platform, 
      price: Math.round(basePrice * (0.9 + Math.random() * 0.2)), 
      available: Math.random() > 0.1, 
      deliveryTime: '8 mins' 
    },
    { 
      platform: 'swiggy' as Platform, 
      price: Math.round(basePrice * (0.93 + Math.random() * 0.3)), 
      available: Math.random() > 0.1, 
      deliveryTime: '15 mins' 
    },
    { 
      platform: 'bigbasket' as Platform, 
      price: Math.round(basePrice * (0.92 + Math.random() * 0.18)), 
      available: Math.random() > 0.1, 
      deliveryTime: '30 mins' 
    },
    { 
      platform: 'dunzo' as Platform, 
      price: Math.round(basePrice * (0.94 + Math.random() * 0.25)), 
      available: Math.random() > 0.1, 
      deliveryTime: '20 mins' 
    },
  ];
};

// Extended categories
const categoriesExtended = [
  'Dairy & Milk',
  'Fruits',
  'Vegetables',
  'Meat & Seafood',
  'Grocery',
  'Snacks',
  'Beverages',
  'Bakery',
  'Frozen Foods',
  'Personal Care',
  'Baby Care',
  'Health & Wellness',
  'Household',
  'Pet Care',
  'Breakfast & Cereal',
  'Condiments & Sauces',
  'Canned Goods',
  'Pasta & Noodles',
  'Rice & Grains',
  'Oils & Ghee',
  'Spices & Seasonings',
  'Organic Foods',
  'Ready to Eat',
  'Sweets & Desserts',
  'Eggs'
];

// Product data for each category
const productsByCategory: Record<string, Array<{name: string, description: string, unit: string, basePrice: number}>> = {
  'Dairy & Milk': [
    {name: 'Fresh Milk', description: 'Farm-fresh whole milk, perfect for your daily needs.', unit: '500ml', basePrice: 30},
    {name: 'Toned Milk', description: 'Low-fat milk with all essential nutrients.', unit: '1L', basePrice: 55},
    {name: 'Greek Yogurt', description: 'Creamy Greek yogurt, high in protein and perfect for breakfast.', unit: '200g', basePrice: 60},
    {name: 'Plain Yogurt', description: 'Traditional yogurt with live cultures for gut health.', unit: '400g', basePrice: 45},
    {name: 'Paneer', description: 'Fresh cottage cheese, rich in protein and calcium.', unit: '200g', basePrice: 75},
    {name: 'Butter', description: 'Creamy unsalted butter for cooking and baking.', unit: '100g', basePrice: 50},
    {name: 'Cheese Slices', description: 'Processed cheese slices, perfect for sandwiches.', unit: '10 slices', basePrice: 120},
    {name: 'Mozzarella Cheese', description: 'Stretchy mozzarella cheese for pizzas and Italian dishes.', unit: '200g', basePrice: 180},
    {name: 'Cheddar Cheese', description: 'Aged cheddar cheese with rich flavor.', unit: '200g', basePrice: 220},
    {name: 'Flavored Yogurt', description: 'Fruit-flavored yogurt with real fruit pieces.', unit: '125g', basePrice: 35},
    {name: 'Cream', description: 'Fresh dairy cream for desserts and cooking.', unit: '200ml', basePrice: 70},
    {name: 'Buttermilk', description: 'Traditional spiced buttermilk for refreshment.', unit: '500ml', basePrice: 30},
    {name: 'Condensed Milk', description: 'Sweetened condensed milk for desserts.', unit: '400g', basePrice: 110},
    {name: 'Cottage Cheese', description: 'Low-fat cottage cheese, perfect for salads.', unit: '200g', basePrice: 65},
    {name: 'Full Cream Milk', description: 'Rich and creamy full-fat milk.', unit: '500ml', basePrice: 35},
    {name: 'Low-Fat Milk', description: 'Reduced fat milk for weight-conscious individuals.', unit: '1L', basePrice: 60},
    {name: 'Sour Cream', description: 'Tangy sour cream for dips and toppings.', unit: '200g', basePrice: 80},
    {name: 'Flavored Milk', description: 'Chocolate flavored milk for kids and adults.', unit: '200ml', basePrice: 30},
    {name: 'Almond Milk', description: 'Plant-based milk alternative made from almonds.', unit: '1L', basePrice: 120},
    {name: 'Soy Milk', description: 'Plant-based milk alternative rich in protein.', unit: '1L', basePrice: 90},
  ],
  'Fruits': [
    {name: 'Organic Bananas', description: 'Sweet and nutritious organic bananas.', unit: '6 pcs', basePrice: 40},
    {name: 'Fresh Apples', description: 'Crisp and juicy apples, rich in fiber.', unit: '4 pcs', basePrice: 120},
    {name: 'Sweet Oranges', description: 'Juicy oranges packed with vitamin C.', unit: '6 pcs', basePrice: 90},
    {name: 'Green Grapes', description: 'Seedless green grapes for a refreshing snack.', unit: '500g', basePrice: 80},
    {name: 'Black Grapes', description: 'Seedless black grapes, sweet and juicy.', unit: '500g', basePrice: 90},
    {name: 'Watermelon', description: 'Sweet and hydrating watermelon, perfect for summer.', unit: '1 pc (2-3kg)', basePrice: 120},
    {name: 'Papaya', description: 'Ripe papaya, rich in vitamins and digestive enzymes.', unit: '1 pc (800g-1kg)', basePrice: 60},
    {name: 'Pineapple', description: 'Sweet and tangy pineapple, rich in bromelain.', unit: '1 pc', basePrice: 80},
    {name: 'Pomegranate', description: 'Antioxidant-rich pomegranate with juicy pearls.', unit: '2 pcs', basePrice: 140},
    {name: 'Sweet Lime', description: 'Refreshing sweet lime, perfect for juicing.', unit: '6 pcs', basePrice: 60},
    {name: 'Mangoes', description: 'Sweet and aromatic mangoes, king of fruits.', unit: '3 pcs', basePrice: 200},
    {name: 'Kiwi', description: 'Tangy kiwi fruit, packed with vitamin C.', unit: '3 pcs', basePrice: 90},
    {name: 'Strawberries', description: 'Sweet and fragrant strawberries for desserts and snacking.', unit: '200g', basePrice: 120},
    {name: 'Blueberries', description: 'Antioxidant-rich blueberries for healthy snacking.', unit: '125g', basePrice: 180},
    {name: 'Guava', description: 'Crunchy guava fruit rich in vitamin C and fiber.', unit: '500g', basePrice: 50},
    {name: 'Custard Apple', description: 'Sweet custard apple with creamy flesh.', unit: '2 pcs', basePrice: 150},
    {name: 'Dragon Fruit', description: 'Exotic dragon fruit with speckled flesh.', unit: '1 pc', basePrice: 90},
    {name: 'Pears', description: 'Juicy and sweet pears for snacking.', unit: '4 pcs', basePrice: 140},
    {name: 'Cherries', description: 'Sweet cherries, rich in antioxidants.', unit: '200g', basePrice: 200},
    {name: 'Plums', description: 'Juicy plums with sweet-tart flavor.', unit: '500g', basePrice: 120},
  ],
  'Vegetables': [
    {name: 'Fresh Tomatoes', description: 'Ripe and juicy tomatoes for your salads and cooking.', unit: '500g', basePrice: 35},
    {name: 'Potatoes', description: 'Fresh potatoes, perfect for curries, fries, and more.', unit: '1kg', basePrice: 40},
    {name: 'Onions', description: 'Essential onions for everyday cooking.', unit: '1kg', basePrice: 35},
    {name: 'Carrots', description: 'Fresh carrots rich in beta-carotene.', unit: '500g', basePrice: 30},
    {name: 'Capsicum', description: 'Crunchy bell peppers for stir-fries and salads.', unit: '500g', basePrice: 60},
    {name: 'Cucumber', description: 'Fresh cucumber for salads and raita.', unit: '500g', basePrice: 30},
    {name: 'Lady Finger', description: 'Tender okra for delicious curry and stir-fry.', unit: '250g', basePrice: 30},
    {name: 'Cauliflower', description: 'Fresh cauliflower for curries and baking.', unit: '1 pc', basePrice: 40},
    {name: 'Cabbage', description: 'Crisp cabbage for salads and stir-fries.', unit: '1 pc', basePrice: 35},
    {name: 'Green Peas', description: 'Fresh green peas, sweet and nutritious.', unit: '250g', basePrice: 40},
    {name: 'Spinach', description: 'Fresh spinach leaves, rich in iron and vitamins.', unit: '250g', basePrice: 30},
    {name: 'Brinjal', description: 'Glossy eggplant for curries and baingan bharta.', unit: '500g', basePrice: 40},
    {name: 'Bitter Gourd', description: 'Fresh bitter gourd for traditional recipes.', unit: '250g', basePrice: 30},
    {name: 'Green Chillies', description: 'Spicy green chillies for adding heat to dishes.', unit: '100g', basePrice: 15},
    {name: 'Ginger', description: 'Fresh ginger for adding flavor to various dishes.', unit: '100g', basePrice: 20},
    {name: 'Garlic', description: 'Essential garlic pods for cooking.', unit: '100g', basePrice: 20},
    {name: 'Mushrooms', description: 'Fresh button mushrooms for curries and stir-fries.', unit: '200g', basePrice: 50},
    {name: 'Sweet Potato', description: 'Nutritious sweet potatoes for healthy meals.', unit: '500g', basePrice: 45},
    {name: 'Beetroot', description: 'Vibrant beetroot for salads and curries.', unit: '500g', basePrice: 40},
    {name: 'Coriander Leaves', description: 'Fresh coriander leaves for garnishing.', unit: '100g', basePrice: 15},
  ],
  'Meat & Seafood': [
    {name: 'Chicken Breast', description: 'Premium boneless chicken breast, fresh and ready to cook.', unit: '500g', basePrice: 180},
    {name: 'Chicken Curry Cut', description: 'Mixed chicken pieces perfect for curries.', unit: '1kg', basePrice: 250},
    {name: 'Chicken Drumsticks', description: 'Juicy chicken drumsticks for grilling and roasting.', unit: '500g', basePrice: 160},
    {name: 'Chicken Wings', description: 'Chicken wings for frying and baking.', unit: '500g', basePrice: 140},
    {name: 'Mutton Curry Cut', description: 'Fresh goat meat, perfect for rich curries.', unit: '500g', basePrice: 350},
    {name: 'Mutton Keema', description: 'Minced goat meat for kebabs and koftas.', unit: '500g', basePrice: 380},
    {name: 'Fish Fillet', description: 'Boneless fish fillets, ready to cook.', unit: '500g', basePrice: 300},
    {name: 'Prawns', description: 'Fresh prawns for curries and stir-fries.', unit: '250g', basePrice: 260},
    {name: 'Rohu Fish', description: 'Fresh river fish, cleaned and ready to cook.', unit: '1 pc (800g-1kg)', basePrice: 200},
    {name: 'Pomfret', description: 'Premium pomfret fish for frying and curries.', unit: '2 pcs (500g)', basePrice: 450},
    {name: 'Lamb Chops', description: 'Tender lamb chops for grilling and barbecue.', unit: '500g', basePrice: 450},
    {name: 'Pork Ribs', description: 'Succulent pork ribs for roasting and barbecue.', unit: '500g', basePrice: 320},
    {name: 'Boneless Mutton', description: 'Tender boneless goat meat for special dishes.', unit: '500g', basePrice: 420},
    {name: 'Crab', description: 'Fresh crab for delicious seafood preparations.', unit: '2 pcs (400g)', basePrice: 300},
    {name: 'Salmon Fillet', description: 'Premium salmon fillet rich in omega-3.', unit: '250g', basePrice: 550},
    {name: 'Turkey Meat', description: 'Lean turkey meat for healthy protein.', unit: '500g', basePrice: 420},
    {name: 'Sardines', description: 'Fresh sardines for frying and curries.', unit: '500g', basePrice: 180},
    {name: 'Fish Curry Cut', description: 'Mixed fish pieces perfect for curry.', unit: '500g', basePrice: 220},
    {name: 'Duck Meat', description: 'Specialty duck meat for roasting.', unit: '500g', basePrice: 380},
    {name: 'Squid', description: 'Fresh squid for frying and seafood dishes.', unit: '250g', basePrice: 240},
  ],
  'Grocery': [
    {name: 'Whole Wheat Bread', description: 'Nutritious whole wheat bread for a healthy breakfast.', unit: '400g', basePrice: 40},
    {name: 'Basmati Rice', description: 'Premium long-grain basmati rice.', unit: '1kg', basePrice: 120},
    {name: 'Toor Dal', description: 'Split pigeon peas for everyday cooking.', unit: '500g', basePrice: 70},
    {name: 'Moong Dal', description: 'Split green gram for soups and sides.', unit: '500g', basePrice: 75},
    {name: 'Chana Dal', description: 'Split chickpeas for nutritious meals.', unit: '500g', basePrice: 65},
    {name: 'Urad Dal', description: 'Split black gram for South Indian dishes.', unit: '500g', basePrice: 80},
    {name: 'White Rice', description: 'Regular white rice for everyday meals.', unit: '5kg', basePrice: 250},
    {name: 'Brown Rice', description: 'Nutritious brown rice with more fiber.', unit: '1kg', basePrice: 90},
    {name: 'Poha', description: 'Flattened rice for quick breakfast.', unit: '500g', basePrice: 45},
    {name: 'Besan', description: 'Gram flour for pakoras and sweets.', unit: '500g', basePrice: 60},
    {name: 'Wheat Flour', description: 'Fine wheat flour for chapatis and rotis.', unit: '5kg', basePrice: 180},
    {name: 'Sugar', description: 'Refined white sugar for cooking and baking.', unit: '1kg', basePrice: 50},
    {name: 'Jaggery', description: 'Natural jaggery blocks for traditional sweetening.', unit: '500g', basePrice: 60},
    {name: 'Table Salt', description: 'Iodized salt for cooking and seasoning.', unit: '1kg', basePrice: 20},
    {name: 'Rock Salt', description: 'Natural rock salt for cooking and remedies.', unit: '500g', basePrice: 35},
    {name: 'Black Pepper', description: 'Whole black peppercorns for grinding.', unit: '100g', basePrice: 80},
    {name: 'Red Chilli Powder', description: 'Spicy red chili powder for Indian cooking.', unit: '200g', basePrice: 90},
    {name: 'Turmeric Powder', description: 'Ground turmeric for color and health.', unit: '200g', basePrice: 60},
    {name: 'Garam Masala', description: 'Blend of aromatic spices for Indian dishes.', unit: '100g', basePrice: 70},
    {name: 'Coriander Powder', description: 'Ground coriander seeds for curry.', unit: '200g', basePrice: 60},
    {name: 'Cumin Seeds', description: 'Aromatic cumin seeds for tempering.', unit: '100g', basePrice: 60},
    {name: 'Mustard Seeds', description: 'Black mustard seeds for tempering.', unit: '100g', basePrice: 40},
    {name: 'Cardamom', description: 'Aromatic cardamom pods for desserts and tea.', unit: '50g', basePrice: 120},
    {name: 'Fennel Seeds', description: 'Sweet fennel seeds for flavoring.', unit: '100g', basePrice: 50},
    {name: 'Cinnamon Sticks', description: 'Aromatic cinnamon for desserts and curries.', unit: '50g', basePrice: 70},
  ],
  'Snacks': [
    {name: 'Potato Chips', description: 'Crunchy potato chips for your snack cravings.', unit: '100g', basePrice: 30},
    {name: 'Salted Peanuts', description: 'Roasted peanuts with a touch of salt.', unit: '200g', basePrice: 60},
    {name: 'Mixed Namkeen', description: 'Traditional Indian savory snack mix.', unit: '400g', basePrice: 80},
    {name: 'Tortilla Chips', description: 'Corn tortilla chips for dips and nachos.', unit: '200g', basePrice: 120},
    {name: 'Popcorn', description: 'Microwave popcorn for movie nights.', unit: '3 packs', basePrice: 90},
    {name: 'Cookies', description: 'Assorted cookies for tea time.', unit: '300g', basePrice: 75},
    {name: 'Chocolate Wafers', description: 'Crispy chocolate wafer biscuits.', unit: '150g', basePrice: 50},
    {name: 'Trail Mix', description: 'Healthy mix of nuts, seeds, and dried fruits.', unit: '200g', basePrice: 180},
    {name: 'Cheese Balls', description: 'Crunchy cheese-flavored corn balls.', unit: '100g', basePrice: 40},
    {name: 'Pretzel Sticks', description: 'Crunchy salted pretzel sticks.', unit: '150g', basePrice: 120},
    {name: 'Rice Cakes', description: 'Light and crispy rice cakes.', unit: '150g', basePrice: 90},
    {name: 'Bhujia Sev', description: 'Thin and spicy gram flour noodles.', unit: '400g', basePrice: 90},
    {name: 'Masala Peanuts', description: 'Spicy coated peanuts for snacking.', unit: '200g', basePrice: 70},
    {name: 'Mini Samosas', description: 'Ready-to-fry mini samosas.', unit: '10 pcs', basePrice: 80},
    {name: 'Chakli', description: 'Spiral-shaped rice flour snack.', unit: '200g', basePrice: 70},
    {name: 'Baked Nachos', description: 'Baked corn chips for healthier snacking.', unit: '150g', basePrice: 110},
    {name: 'Multigrain Chips', description: 'Healthy chips made with multiple grains.', unit: '100g', basePrice: 70},
    {name: 'Kaju Mixture', description: 'Cashew-based savory snack mix.', unit: '200g', basePrice: 160},
    {name: 'Banana Chips', description: 'Crispy banana chips with a touch of salt.', unit: '200g', basePrice: 80},
    {name: 'Roasted Chana', description: 'Roasted chickpeas for healthy snacking.', unit: '200g', basePrice: 60},
  ],
  'Beverages': [
    {name: 'Cola Soft Drink', description: 'Refreshing cola drink for instant energy.', unit: '1L', basePrice: 65},
    {name: 'Orange Juice', description: 'Natural orange juice without preservatives.', unit: '1L', basePrice: 120},
    {name: 'Mango Juice', description: 'Sweet mango juice for refreshment.', unit: '1L', basePrice: 130},
    {name: 'Mixed Fruit Juice', description: 'Blend of multiple fruits for nutrition.', unit: '1L', basePrice: 110},
    {name: 'Coconut Water', description: 'Natural coconut water for hydration.', unit: '200ml', basePrice: 40},
    {name: 'Lemonade', description: 'Refreshing lemon drink for summer.', unit: '500ml', basePrice: 40},
    {name: 'Iced Tea', description: 'Lemon-flavored iced tea.', unit: '500ml', basePrice: 50},
    {name: 'Energy Drink', description: 'Energy-boosting drink for active lifestyles.', unit: '250ml', basePrice: 90},
    {name: 'Sparkling Water', description: 'Refreshing carbonated water.', unit: '750ml', basePrice: 80},
    {name: 'Green Tea', description: 'Healthy green tea bags for antioxidants.', unit: '25 bags', basePrice: 220},
    {name: 'Black Tea', description: 'Premium black tea leaves.', unit: '250g', basePrice: 150},
    {name: 'Instant Coffee', description: 'Quick instant coffee powder.', unit: '200g', basePrice: 350},
    {name: 'Filter Coffee', description: 'Traditional South Indian filter coffee.', unit: '500g', basePrice: 280},
    {name: 'Hot Chocolate', description: 'Rich hot chocolate mix for cozy evenings.', unit: '200g', basePrice: 150},
    {name: 'Apple Juice', description: 'Pure apple juice without added sugar.', unit: '1L', basePrice: 120},
    {name: 'Grape Juice', description: 'Natural grape juice for refreshment.', unit: '1L', basePrice: 130},
    {name: 'Tonic Water', description: 'Classic tonic water for mixers.', unit: '300ml', basePrice: 70},
    {name: 'Herbal Tea', description: 'Calming herbal tea bags for relaxation.', unit: '20 bags', basePrice: 180},
    {name: 'Almond Milk', description: 'Plant-based milk alternative.', unit: '1L', basePrice: 220},
    {name: 'Sports Drink', description: 'Electrolyte-rich drink for athletes.', unit: '500ml', basePrice: 60},
  ],
  'Bakery': [
    {name: 'White Bread', description: 'Soft white bread for sandwiches and toast.', unit: '400g', basePrice: 35},
    {name: 'Brown Bread', description: 'Nutritious brown bread for healthy meals.', unit: '400g', basePrice: 40},
    {name: 'Multigrain Bread', description: 'Hearty bread with multiple grains and seeds.', unit: '400g', basePrice: 55},
    {name: 'Burger Buns', description: 'Soft buns perfect for burgers.', unit: '4 pcs', basePrice: 45},
    {name: 'Hot Dog Rolls', description: 'Elongated rolls for hot dogs.', unit: '4 pcs', basePrice: 50},
    {name: 'Croissants', description: 'Buttery flaky pastry for breakfast.', unit: '2 pcs', basePrice: 80},
    {name: 'Donuts', description: 'Sweet ring-shaped fried dough.', unit: '2 pcs', basePrice: 60},
    {name: 'Muffins', description: 'Assorted muffins for snacking.', unit: '4 pcs', basePrice: 120},
    {name: 'Dinner Rolls', description: 'Soft rolls perfect for dinner.', unit: '6 pcs', basePrice: 60},
    {name: 'Bagels', description: 'Chewy ring-shaped bread for breakfast.', unit: '4 pcs', basePrice: 150},
    {name: 'Pita Bread', description: 'Flat bread with pocket for sandwiches.', unit: '6 pcs', basePrice: 70},
    {name: 'Focaccia', description: 'Italian flatbread with herbs.', unit: '1 pc', basePrice: 120},
    {name: 'Garlic Bread', description: 'Bread with garlic butter, ready to bake.', unit: '1 pc', basePrice: 90},
    {name: 'Fruit Cake', description: 'Sweet cake with dried fruits.', unit: '500g', basePrice: 200},
    {name: 'Chocolate Cake', description: 'Rich chocolate cake for celebrations.', unit: '500g', basePrice: 300},
    {name: 'Vanilla Pound Cake', description: 'Simple vanilla cake for tea time.', unit: '300g', basePrice: 150},
    {name: 'Cupcakes', description: 'Assorted small cakes with frosting.', unit: '6 pcs', basePrice: 180},
    {name: 'Cookies', description: 'Assorted cookies for tea time.', unit: '200g', basePrice: 120},
    {name: 'Breadsticks', description: 'Crunchy breadsticks for appetizers.', unit: '150g', basePrice: 80},
    {name: 'Cinnamon Rolls', description: 'Sweet rolls with cinnamon and icing.', unit: '4 pcs', basePrice: 160},
  ],
  'Frozen Foods': [
    {name: 'Frozen Peas', description: 'Garden fresh peas, frozen for convenience.', unit: '500g', basePrice: 80},
    {name: 'Mixed Vegetables', description: 'Assorted vegetables, frozen for quick cooking.', unit: '500g', basePrice: 120},
    {name: 'Frozen Corn', description: 'Sweet corn kernels, frozen for freshness.', unit: '500g', basePrice: 100},
    {name: 'Frozen Berries', description: 'Mixed berries for smoothies and desserts.', unit: '300g', basePrice: 250},
    {name: 'French Fries', description: 'Ready-to-cook frozen potato fries.', unit: '500g', basePrice: 120},
    {name: 'Frozen Pizza', description: 'Ready-to-bake margherita pizza.', unit: '1 pc', basePrice: 220},
    {name: 'Ice Cream Vanilla', description: 'Creamy vanilla ice cream for dessert.', unit: '500ml', basePrice: 180},
    {name: 'Ice Cream Chocolate', description: 'Rich chocolate ice cream for indulgence.', unit: '500ml', basePrice: 200},
    {name: 'Ice Cream Strawberry', description: 'Sweet strawberry ice cream with real fruit.', unit: '500ml', basePrice: 190},
    {name: 'Frozen Paratha', description: 'Ready-to-cook layered flatbread.', unit: '5 pcs', basePrice: 110},
    {name: 'Frozen Meatballs', description: 'Seasoned meatballs ready to cook.', unit: '500g', basePrice: 320},
    {name: 'Frozen Samosas', description: 'Traditional Indian snack, ready to fry.', unit: '10 pcs', basePrice: 150},
    {name: 'Frozen Spring Rolls', description: 'Vegetable-filled rolls for appetizers.', unit: '10 pcs', basePrice: 160},
    {name: 'Frozen Fish Fingers', description: 'Breaded fish fingers for quick meals.', unit: '300g', basePrice: 250},
    {name: 'Chicken Nuggets', description: 'Breaded chicken nuggets for kids.', unit: '400g', basePrice: 280},
    {name: 'Frozen Spinach', description: 'Chopped spinach leaves for quick cooking.', unit: '300g', basePrice: 80},
    {name: 'Frozen Mango', description: 'Diced mango for smoothies and desserts.', unit: '300g', basePrice: 180},
    {name: 'Garlic Bread', description: 'Ready-to-bake garlic bread with herbs.', unit: '2 pcs', basePrice: 100},
  ],
  'Personal Care': [
    {name: 'Shampoo', description: 'Gentle shampoo for normal hair.', unit: '400ml', basePrice: 180},
    {name: 'Conditioner', description: 'Nourishing conditioner for soft hair.', unit: '400ml', basePrice: 200},
    {name: 'Body Wash', description: 'Refreshing body wash for daily use.', unit: '500ml', basePrice: 220},
    {name: 'Hand Soap', description: 'Antibacterial hand soap for hygiene.', unit: '250ml', basePrice: 80},
    {name: 'Toothpaste', description: 'Fluoride toothpaste for cavity protection.', unit: '150g', basePrice: 90},
    {name: 'Toothbrush', description: 'Medium soft bristle toothbrush.', unit: '1 pc', basePrice: 40},
    {name: 'Dental Floss', description: 'Mint-flavored dental floss for oral hygiene.', unit: '50m', basePrice: 120},
    {name: 'Mouthwash', description: 'Antiseptic mouthwash for fresh breath.', unit: '500ml', basePrice: 140},
    {name: 'Deodorant Roll-on', description: 'Long-lasting roll-on deodorant.', unit: '50ml', basePrice: 120},
    {name: 'Deodorant Spray', description: 'Quick-dry spray deodorant.', unit: '150ml', basePrice: 180},
    {name: 'Body Lotion', description: 'Moisturizing body lotion for dry skin.', unit: '400ml', basePrice: 180},
    {name: 'Face Wash', description: 'Gentle face wash for daily cleansing.', unit: '150ml', basePrice: 150},
    {name: 'Face Moisturizer', description: 'Hydrating face cream for all skin types.', unit: '100ml', basePrice: 220},
    {name: 'Sunscreen', description: 'SPF 50 sunscreen for UV protection.', unit: '100ml', basePrice: 350},
    {name: 'Hand Cream', description: 'Intensive hand cream for dry hands.', unit: '75ml', basePrice: 120},
    {name: 'Lip Balm', description: 'Moisturizing lip balm for chapped lips.', unit: '4.5g', basePrice: 80},
    {name: 'Shaving Cream', description: 'Protective cream for smooth shaving.', unit: '200ml', basePrice: 150},
    {name: 'After Shave', description: 'Soothing after shave lotion.', unit: '100ml', basePrice: 180},
    {name: 'Hair Gel', description: 'Strong-hold hair styling gel.', unit: '150ml', basePrice: 160},
    {name: 'Cotton Swabs', description: 'Multipurpose cotton buds for hygiene.', unit: '200 pcs', basePrice: 70},
  ],
  'Baby Care': [
    {name: 'Baby Diapers', description: 'Super absorbent diapers for babies.', unit: '30 pcs', basePrice: 450},
    {name: 'Baby Wipes', description: 'Gentle alcohol-free baby wipes.', unit: '72 pcs', basePrice: 120},
    {name: 'Baby Shampoo', description: 'Tear-free gentle baby shampoo.', unit: '200ml', basePrice: 180},
    {name: 'Baby Soap', description: 'Mild soap specially for baby skin.', unit: '75g', basePrice: 60},
    {name: 'Baby Lotion', description: 'Gentle moisturizing lotion for babies.', unit: '200ml', basePrice: 160},
    {name: 'Baby Powder', description: 'Talc-free baby powder for freshness.', unit: '100g', basePrice: 120},
    {name: 'Baby Oil', description: 'Gentle oil for baby massage.', unit: '200ml', basePrice: 150},
    {name: 'Diaper Rash Cream', description: 'Protective cream for diaper rash.', unit: '50g', basePrice: 180},
    {name: 'Baby Food - Cereal', description: 'Rice-based cereal for infants.', unit: '300g', basePrice: 220},
    {name: 'Baby Food - Fruit Puree', description: 'Natural fruit puree for babies.', unit: '120g', basePrice: 90},
    {name: 'Baby Food - Veggie Puree', description: 'Nutritious vegetable puree for babies.', unit: '120g', basePrice: 90},
    {name: 'Baby Feeding Bottle', description: 'BPA-free baby feeding bottle.', unit: '1 pc', basePrice: 280},
    {name: 'Baby Nipples', description: 'Silicone nipples for feeding bottles.', unit: '2 pcs', basePrice: 120},
    {name: 'Pacifier', description: 'Orthodontic pacifier for babies.', unit: '1 pc', basePrice: 150},
    {name: 'Teether', description: 'Cooling teether for teething babies.', unit: '1 pc', basePrice: 180},
    {name: 'Baby Toothbrush', description: 'Soft bristle first toothbrush for babies.', unit: '1 pc', basePrice: 70},
    {name: 'Baby Nail Clipper', description: 'Safe nail clipper for babies.', unit: '1 pc', basePrice: 120},
    {name: 'Baby Bathtub', description: 'Portable bathtub for safe bathing.', unit: '1 pc', basePrice: 650},
    {name: 'Baby Detergent', description: 'Mild detergent for baby clothes.', unit: '500ml', basePrice: 220},
    {name: 'Baby Blanket', description: 'Soft blanket for newborns.', unit: '1 pc', basePrice: 350},
  ],
  'Health & Wellness': [
    {name: 'Multivitamin Tablets', description: 'Daily multivitamin supplement for adults.', unit: '60 tabs', basePrice: 450},
    {name: 'Vitamin C Tablets', description: 'Immune-boosting vitamin C supplement.', unit: '60 tabs', basePrice: 320},
    {name: 'Calcium Tablets', description: 'Calcium supplement for bone health.', unit: '60 tabs', basePrice: 280},
    {name: 'Omega-3 Capsules', description: 'Fish oil capsules for heart health.', unit: '60 caps', basePrice: 550},
    {name: 'Protein Powder', description: 'Whey protein supplement for fitness.', unit: '500g', basePrice: 1200},
    {name: 'Glucose Powder', description: 'Energy-boosting glucose powder.', unit: '500g', basePrice: 180},
    {name: 'Band-Aids', description: 'Assorted sizes of adhesive bandages.', unit: '30 pcs', basePrice: 80},
    {name: 'Antiseptic Liquid', description: 'Antiseptic solution for wounds.', unit: '100ml', basePrice: 90},
    {name: 'Antiseptic Cream', description: 'Healing cream for minor cuts and burns.', unit: '20g', basePrice: 70},
    {name: 'Pain Relief Balm', description: 'Soothing balm for muscle pain.', unit: '30g', basePrice: 120},
    {name: 'Pain Relief Spray', description: 'Fast-acting spray for muscle pain.', unit: '100ml', basePrice: 180},
    {name: 'Digital Thermometer', description: 'Accurate digital thermometer for fever.', unit: '1 pc', basePrice: 320},
    {name: 'BP Monitor', description: 'Digital blood pressure monitor.', unit: '1 pc', basePrice: 1800},
    {name: 'Hot Water Bottle', description: 'Rubber hot water bottle for pain relief.', unit: '1 pc', basePrice: 280},
    {name: 'Heating Pad', description: 'Electric heating pad for pain.', unit: '1 pc', basePrice: 650},
    {name: 'Cotton Balls', description: 'Sterile cotton balls for first aid.', unit: '100 pcs', basePrice: 60},
    {name: 'First Aid Kit', description: 'Basic first aid supplies in portable case.', unit: '1 pc', basePrice: 580},
    {name: 'Mosquito Repellent', description: 'Chemical-free mosquito repellent.', unit: '100ml', basePrice: 150},
    {name: 'Hand Sanitizer', description: 'Alcohol-based hand sanitizer.', unit: '500ml', basePrice: 220},
    {name: 'Face Masks', description: 'Disposable face masks for protection.', unit: '10 pcs', basePrice: 150},
  ],
  'Household': [
    {name: 'Laundry Detergent', description: 'Powerful detergent for clean clothes.', unit: '1kg', basePrice: 180},
    {name: 'Fabric Softener', description: 'Fragrant softener for fresh laundry.', unit: '800ml', basePrice: 160},
    {name: 'Dishwashing Liquid', description: 'Grease-cutting dishwashing liquid.', unit: '750ml', basePrice: 150},
    {name: 'Floor Cleaner', description: 'Disinfecting floor cleaning solution.', unit: '1L', basePrice: 130},
    {name: 'Glass Cleaner', description: 'Streak-free glass and mirror cleaner.', unit: '500ml', basePrice: 90},
    {name: 'Toilet Cleaner', description: 'Powerful toilet bowl cleaner.', unit: '500ml', basePrice: 120},
    {name: 'Bleach', description: 'Disinfecting bleach for whites.', unit: '1L', basePrice: 90},
    {name: 'Kitchen Wipes', description: 'Multi-purpose kitchen cleaning wipes.', unit: '80 pcs', basePrice: 150},
    {name: 'Garbage Bags', description: 'Durable plastic garbage bags.', unit: '30 pcs', basePrice: 120},
    {name: 'Air Freshener', description: 'Long-lasting room air freshener.', unit: '300ml', basePrice: 150},
    {name: 'Mosquito Repellent', description: 'Electric mosquito repellent with refill.', unit: '1 pc', basePrice: 120},
    {name: 'Dish Sponge', description: 'Dual-sided kitchen scrub sponge.', unit: '3 pcs', basePrice: 60},
    {name: 'Steel Wool', description: 'Steel wool scrubbers for tough stains.', unit: '10 pcs', basePrice: 40},
    {name: 'Aluminum Foil', description: 'Heavy-duty kitchen aluminum foil.', unit: '10m', basePrice: 120},
    {name: 'Plastic Wrap', description: 'Food-grade plastic cling film.', unit: '30m', basePrice: 80},
    {name: 'Paper Towels', description: 'Absorbent kitchen paper towels.', unit: '2 rolls', basePrice: 80},
    {name: 'Toilet Paper', description: 'Soft toilet tissue paper.', unit: '6 rolls', basePrice: 160},
    {name: 'Facial Tissue', description: 'Soft facial tissues for everyday use.', unit: '200 pcs', basePrice: 100},
    {name: 'Napkins', description: 'Paper table napkins for dining.', unit: '100 pcs', basePrice: 80},
    {name: 'Rubber Gloves', description: 'Durable rubber gloves for cleaning.', unit: '1 pair', basePrice: 60},
  ],
  'Pet Care': [
    {name: 'Dog Food', description: 'Balanced dry food for adult dogs.', unit: '3kg', basePrice: 850},
    {name: 'Cat Food', description: 'Protein-rich dry food for cats.', unit: '1.5kg', basePrice: 650},
    {name: 'Fish Food', description: 'Nutritious flakes for aquarium fish.', unit: '100g', basePrice: 180},
    {name: 'Dog Treats', description: 'Chewy treats for training and rewards.', unit: '200g', basePrice: 220},
    {name: 'Cat Treats', description: 'Crunchy treats for feline friends.', unit: '60g', basePrice: 150},
    {name: 'Pet Shampoo', description: 'Gentle shampoo for dogs and cats.', unit: '300ml', basePrice: 280},
    {name: 'Pet Conditioner', description: 'Detangling conditioner for pets.', unit: '300ml', basePrice: 320},
    {name: 'Flea & Tick Spray', description: 'Protective spray against parasites.', unit: '250ml', basePrice: 380},
    {name: 'Pet Brush', description: 'Grooming brush for pet fur.', unit: '1 pc', basePrice: 250},
    {name: 'Dog Leash', description: 'Durable nylon leash for walking.', unit: '1 pc', basePrice: 350},
    {name: 'Dog Collar', description: 'Adjustable collar for dogs.', unit: '1 pc', basePrice: 280},
    {name: 'Cat Litter', description: 'Clumping cat litter for odor control.', unit: '5kg', basePrice: 450},
    {name: 'Litter Box', description: 'Covered litter box for cats.', unit: '1 pc', basePrice: 850},
    {name: 'Pet Bowl', description: 'Stainless steel food and water bowl.', unit: '1 pc', basePrice: 250},
    {name: 'Pet Bed', description: 'Soft cushioned bed for dogs and cats.', unit: '1 pc', basePrice: 1200},
    {name: 'Pet Toys', description: 'Assorted toys for entertainment.', unit: '3 pcs', basePrice: 350},
    {name: 'Pet Nail Clipper', description: 'Safe nail trimmer for pets.', unit: '1 pc', basePrice: 180},
    {name: 'Aquarium Filter', description: 'Water filter for fish tanks.', unit: '1 pc', basePrice: 450},
    {name: 'Bird Seeds', description: 'Mixed seeds for pet birds.', unit: '1kg', basePrice: 320},
    {name: 'Pet Carrier', description: 'Portable carrier for small pets.', unit: '1 pc', basePrice: 1500},
  ],
  'Breakfast & Cereal': [
    {name: 'Corn Flakes', description: 'Crunchy corn flakes for breakfast.', unit: '500g', basePrice: 180},
    {name: 'Muesli', description: 'Nutritious mix of oats, nuts, and dried fruits.', unit: '500g', basePrice: 320},
    {name: 'Oats', description: 'Rolled oats for healthy breakfast.', unit: '1kg', basePrice: 180},
    {name: 'Granola', description: 'Crunchy granola with honey and nuts.', unit: '400g', basePrice: 350},
    {name: 'Wheat Flakes', description: 'Whole wheat flakes cereal.', unit: '500g', basePrice: 190},
    {name: 'Bran Flakes', description: 'High-fiber bran cereal flakes.', unit: '500g', basePrice: 220},
    {name: 'Chocolate Cereal', description: 'Chocolate-flavored breakfast cereal.', unit: '375g', basePrice: 250},
    {name: 'Rice Krispies', description: 'Crispy rice cereal for breakfast.', unit: '340g', basePrice: 220},
    {name: 'Porridge', description: 'Instant porridge for quick breakfast.', unit: '500g', basePrice: 160},
    {name: 'Cereal Bars', description: 'Convenient breakfast bars with fruits.', unit: '6 pcs', basePrice: 180},
    {name: 'Pancake Mix', description: 'Ready-to-cook pancake batter mix.', unit: '500g', basePrice: 160},
    {name: 'Waffle Mix', description: 'Ready-to-cook waffle batter mix.', unit: '500g', basePrice: 180},
    {name: 'Maple Syrup', description: 'Pure maple syrup for pancakes.', unit: '250ml', basePrice: 380},
    {name: 'Honey', description: 'Pure natural honey for breakfast.', unit: '250g', basePrice: 180},
    {name: 'Jam', description: 'Mixed fruit jam for bread and toast.', unit: '300g', basePrice: 120},
    {name: 'Peanut Butter', description: 'Creamy peanut butter spread.', unit: '340g', basePrice: 180},
    {name: 'Chocolate Spread', description: 'Hazelnut chocolate spread for bread.', unit: '350g', basePrice: 320},
    {name: 'Instant Coffee', description: 'Quick dissolving coffee granules.', unit: '200g', basePrice: 280},
    {name: 'Tea Bags', description: 'Black tea bags for morning brew.', unit: '100 bags', basePrice: 180},
    {name: 'Hot Chocolate Mix', description: 'Sweet chocolate powder for hot drinks.', unit: '400g', basePrice: 220},
  ],
  'Condiments & Sauces': [
    {name: 'Tomato Ketchup', description: 'Classic tomato ketchup for burgers and fries.', unit: '500g', basePrice: 120},
    {name: 'Mayonnaise', description: 'Creamy mayonnaise for sandwiches and dips.', unit: '500g', basePrice: 180},
    {name: 'Mustard Sauce', description: 'Tangy mustard sauce for hotdogs.', unit: '200g', basePrice: 120},
    {name: 'Soy Sauce', description: 'Traditional soy sauce for Asian cooking.', unit: '200ml', basePrice: 90},
    {name: 'Chili Sauce', description: 'Spicy chili sauce for heat lovers.', unit: '200g', basePrice: 80},
    {name: 'Pasta Sauce', description: 'Tomato-based sauce for pasta dishes.', unit: '400g', basePrice: 150},
    {name: 'BBQ Sauce', description: 'Smoky barbecue sauce for grilling.', unit: '300g', basePrice: 140},
    {name: 'Hot Sauce', description: 'Fiery hot sauce for spice lovers.', unit: '60ml', basePrice: 120},
    {name: 'Worcestershire Sauce', description: 'Classic English sauce for meats.', unit: '150ml', basePrice: 180},
    {name: 'Fish Sauce', description: 'Traditional Thai fish sauce.', unit: '200ml', basePrice: 110},
    {name: 'Vinegar', description: 'White vinegar for cooking and cleaning.', unit: '500ml', basePrice: 60},
    {name: 'Apple Cider Vinegar', description: 'Natural apple cider vinegar with mother.', unit: '500ml', basePrice: 220},
    {name: 'Olive Oil', description: 'Extra virgin olive oil for cooking.', unit: '500ml', basePrice: 450},
    {name: 'Vegetable Oil', description: 'Refined vegetable oil for cooking.', unit: '1L', basePrice: 160},
    {name: 'Coconut Oil', description: 'Virgin coconut oil for cooking and skin.', unit: '500ml', basePrice: 380},
    {name: 'Sesame Oil', description: 'Aromatic sesame oil for Asian cuisine.', unit: '200ml', basePrice: 180},
    {name: 'Honey', description: 'Pure natural honey as sweetener.', unit: '500g', basePrice: 280},
    {name: 'Maple Syrup', description: 'Grade A maple syrup for pancakes.', unit: '250ml', basePrice: 450},
    {name: 'Salad Dressing', description: 'Italian herb salad dressing.', unit: '250ml', basePrice: 180},
    {name: 'Pickle', description: 'Mixed vegetable pickle in oil.', unit: '400g', basePrice: 120},
  ],
  'Canned Goods': [
    {name: 'Baked Beans', description: 'Baked beans in tomato sauce.', unit: '400g', basePrice: 60},
    {name: 'Chickpeas', description: 'Cooked chickpeas in water.', unit: '400g', basePrice: 70},
    {name: 'Red Kidney Beans', description: 'Cooked red kidney beans for quick meals.', unit: '400g', basePrice: 70},
    {name: 'Black Beans', description: 'Cooked black beans for Mexican cuisine.', unit: '400g', basePrice: 80},
    {name: 'Sweet Corn', description: 'Whole kernel sweet corn in water.', unit: '400g', basePrice: 80},
    {name: 'Tuna', description: 'Chunk light tuna in water.', unit: '185g', basePrice: 120},
    {name: 'Sardines', description: 'Sardines in tomato sauce.', unit: '200g', basePrice: 90},
    {name: 'Tomato Puree', description: 'Concentrated tomato puree for cooking.', unit: '400g', basePrice: 60},
    {name: 'Diced Tomatoes', description: 'Chopped tomatoes in juice.', unit: '400g', basePrice: 70},
    {name: 'Tomato Paste', description: 'Thick tomato paste for cooking.', unit: '200g', basePrice: 50},
    {name: 'Condensed Milk', description: 'Sweetened condensed milk for desserts.', unit: '397g', basePrice: 120},
    {name: 'Evaporated Milk', description: 'Unsweetened evaporated milk.', unit: '400g', basePrice: 80},
    {name: 'Coconut Milk', description: 'Creamy coconut milk for curries.', unit: '400ml', basePrice: 90},
    {name: 'Mushrooms', description: 'Sliced mushrooms in water.', unit: '285g', basePrice: 100},
    {name: 'Mixed Vegetables', description: 'Assorted vegetables in water.', unit: '400g', basePrice: 80},
    {name: 'Pineapple Slices', description: 'Pineapple rings in light syrup.', unit: '400g', basePrice: 90},
    {name: 'Peach Halves', description: 'Peach halves in light syrup.', unit: '400g', basePrice: 120},
    {name: 'Mixed Fruit', description: 'Fruit cocktail in light syrup.', unit: '400g', basePrice: 100},
    {name: 'Olives', description: 'Green olives with pit in brine.', unit: '340g', basePrice: 180},
    {name: 'Soup', description: 'Ready-to-eat tomato soup.', unit: '400g', basePrice: 70},
  ],
  'Pasta & Noodles': [
    {name: 'Spaghetti', description: 'Traditional Italian spaghetti pasta.', unit: '500g', basePrice: 80},
    {name: 'Penne', description: 'Tubular penne pasta for baked dishes.', unit: '500g', basePrice: 85},
    {name: 'Fusilli', description: 'Spiral pasta perfect for sauce.', unit: '500g', basePrice: 85},
    {name: 'Macaroni', description: 'Elbow macaroni for mac and cheese.', unit: '500g', basePrice: 80},
    {name: 'Lasagna Sheets', description: 'Flat pasta sheets for lasagna.', unit: '250g', basePrice: 120},
    {name: 'Fettuccine', description: 'Flat ribbon pasta for creamy sauces.', unit: '500g', basePrice: 90},
    {name: 'Farfalle', description: 'Bow-tie shaped pasta.', unit: '500g', basePrice: 90},
    {name: 'Whole Wheat Pasta', description: 'Nutritious whole wheat spaghetti.', unit: '500g', basePrice: 120},
    {name: 'Pasta Sauce', description: 'Arrabbiata pasta sauce with herbs.', unit: '500g', basePrice: 180},
    {name: 'Instant Noodles', description: 'Quick-cooking instant noodles.', unit: '5 packs', basePrice: 80},
    {name: 'Cup Noodles', description: 'Ready-to-eat noodles in a cup.', unit: '3 cups', basePrice: 120},
    {name: 'Hakka Noodles', description: 'Chinese-style stir-fry noodles.', unit: '200g', basePrice: 50},
    {name: 'Rice Noodles', description: 'Thin rice noodles for Asian dishes.', unit: '200g', basePrice: 60},
    {name: 'Ramen', description: 'Japanese-style ramen noodles.', unit: '5 packs', basePrice: 150},
    {name: 'Udon Noodles', description: 'Thick Japanese udon noodles.', unit: '200g', basePrice: 120},
    {name: 'Vermicelli', description: 'Thin rice vermicelli noodles.', unit: '500g', basePrice: 80},
    {name: 'Pasta Seasoning', description: 'Italian herb mix for pasta dishes.', unit: '50g', basePrice: 120},
    {name: 'Cheese Sauce', description: 'Creamy cheese sauce for pasta.', unit: '250g', basePrice: 150},
    {name: 'Soba Noodles', description: 'Japanese buckwheat noodles.', unit: '250g', basePrice: 180},
    {name: 'Egg Noodles', description: 'Fresh egg noodles for soups.', unit: '400g', basePrice: 90},
  ],
  'Rice & Grains': [
    {name: 'Basmati Rice', description: 'Aromatic long-grain basmati rice.', unit: '5kg', basePrice: 450},
    {name: 'Jasmine Rice', description: 'Fragrant Thai jasmine rice.', unit: '5kg', basePrice: 480},
    {name: 'Brown Rice', description: 'Nutritious whole grain brown rice.', unit: '2kg', basePrice: 180},
    {name: 'White Rice', description: 'Everyday short-grain white rice.', unit: '5kg', basePrice: 320},
    {name: 'Sona Masoori Rice', description: 'Medium-grain rice for daily meals.', unit: '5kg', basePrice: 380},
    {name: 'Arborio Rice', description: 'Italian rice for creamy risotto.', unit: '1kg', basePrice: 220},
    {name: 'Black Rice', description: 'Nutritious black rice rich in antioxidants.', unit: '500g', basePrice: 150},
    {name: 'Red Rice', description: 'Wholesome red rice with nutty flavor.', unit: '1kg', basePrice: 160},
    {name: 'Quinoa', description: 'Protein-rich ancient grain.', unit: '500g', basePrice: 250},
    {name: 'Bulgur Wheat', description: 'Cracked wheat grain for salads.', unit: '500g', basePrice: 120},
    {name: 'Couscous', description: 'Quick-cooking small pasta grain.', unit: '500g', basePrice: 130},
    {name: 'Millet', description: 'Ancient grain for porridge and sides.', unit: '500g', basePrice: 110},
    {name: 'Pearl Barley', description: 'Versatile grain for soups and stews.', unit: '500g', basePrice: 90},
    {name: 'Polenta', description: 'Coarse ground cornmeal for Italian dishes.', unit: '500g', basePrice: 100},
    {name: 'Wild Rice', description: 'Nutritious wild rice with nutty flavor.', unit: '250g', basePrice: 180},
    {name: 'Rice Flour', description: 'Gluten-free flour from rice.', unit: '500g', basePrice: 80},
    {name: 'Semolina', description: 'Coarse wheat flour for pasta making.', unit: '500g', basePrice: 70},
    {name: 'Flaxseed', description: 'Omega-3 rich seeds for smoothies.', unit: '250g', basePrice: 120},
    {name: 'Chia Seeds', description: 'Nutrient-dense tiny seeds for health.', unit: '200g', basePrice: 180},
  ],
  'Oils & Ghee': [
    {name: 'Sunflower Oil', description: 'Light cooking oil for everyday use.', unit: '1L', basePrice: 120},
    {name: 'Olive Oil', description: 'Extra virgin olive oil for salads.', unit: '500ml', basePrice: 350},
    {name: 'Mustard Oil', description: 'Strong-flavored oil for Indian cooking.', unit: '1L', basePrice: 180},
    {name: 'Groundnut Oil', description: 'High smoke point oil for frying.', unit: '1L', basePrice: 160},
    {name: 'Coconut Oil', description: 'Pure coconut oil for cooking and skin.', unit: '500ml', basePrice: 280},
    {name: 'Rice Bran Oil', description: 'Heart-healthy cooking oil.', unit: '1L', basePrice: 150},
    {name: 'Sesame Oil', description: 'Aromatic oil for Asian cuisines.', unit: '250ml', basePrice: 150},
    {name: 'Ghee', description: 'Clarified butter for Indian cooking.', unit: '500ml', basePrice: 320},
    {name: 'Butter', description: 'Salted table butter for cooking.', unit: '500g', basePrice: 250},
    {name: 'Margarine', description: 'Vegetable-based spread for baking.', unit: '500g', basePrice: 120},
    {name: 'Avocado Oil', description: 'Premium oil rich in monounsaturated fats.', unit: '250ml', basePrice: 380},
    {name: 'Walnut Oil', description: 'Specialty oil for salad dressing.', unit: '250ml', basePrice: 420},
    {name: 'Corn Oil', description: 'Light flavor oil for baking.', unit: '1L', basePrice: 130},
    {name: 'Canola Oil', description: 'Heart-healthy oil for cooking.', unit: '1L', basePrice: 140},
    {name: 'Palm Oil', description: 'High smoke point oil for frying.', unit: '1L', basePrice: 120},
    {name: 'Truffle Oil', description: 'Gourmet oil for finishing dishes.', unit: '100ml', basePrice: 450},
    {name: 'Flaxseed Oil', description: 'Omega-3 rich oil for cold dishes.', unit: '250ml', basePrice: 320},
    {name: 'Grapeseed Oil', description: 'Light oil with high smoke point.', unit: '500ml', basePrice: 280},
    {name: 'Almond Oil', description: 'Sweet oil for baking and skin care.', unit: '250ml', basePrice: 350},
    {name: 'Peanut Butter', description: 'Creamy spread made from peanuts.', unit: '340g', basePrice: 180},
  ],
  'Spices & Seasonings': [
    {name: 'Black Pepper', description: 'Whole black peppercorns for grinding.', unit: '100g', basePrice: 90},
    {name: 'Red Chilli Powder', description: 'Spicy red chili powder for heat.', unit: '100g', basePrice: 80},
    {name: 'Turmeric Powder', description: 'Ground turmeric for color and health.', unit: '100g', basePrice: 70},
    {name: 'Cumin Seeds', description: 'Aromatic seeds for tempering.', unit: '100g', basePrice: 80},
    {name: 'Coriander Powder', description: 'Ground coriander for curries.', unit: '100g', basePrice: 70},
    {name: 'Garam Masala', description: 'Blend of aromatic Indian spices.', unit: '100g', basePrice: 120},
    {name: 'Cinnamon Sticks', description: 'Aromatic bark for flavoring.', unit: '50g', basePrice: 100},
    {name: 'Cardamom', description: 'Green cardamom pods for sweets and tea.', unit: '50g', basePrice: 150},
    {name: 'Cloves', description: 'Aromatic flower buds for spicing.', unit: '50g', basePrice: 130},
    {name: 'Bay Leaves', description: 'Aromatic leaves for flavor and aroma.', unit: '25g', basePrice: 40},
    {name: 'Fennel Seeds', description: 'Sweet anise-like seeds for cooking.', unit: '100g', basePrice: 80},
    {name: 'Mustard Seeds', description: 'Black mustard seeds for tempering.', unit: '100g', basePrice: 60},
    {name: 'Fenugreek Seeds', description: 'Bitter seeds for pickles and curries.', unit: '100g', basePrice: 70},
    {name: 'Oregano', description: 'Dried oregano leaves for Italian dishes.', unit: '50g', basePrice: 90},
    {name: 'Mixed Herbs', description: 'Blend of dried herbs for cooking.', unit: '30g', basePrice: 120},
    {name: 'Paprika', description: 'Sweet or smoky ground peppers.', unit: '50g', basePrice: 80},
    {name: 'Thyme', description: 'Dried thyme leaves for flavoring.', unit: '30g', basePrice: 70},
    {name: 'Rosemary', description: 'Dried rosemary needles for roasts.', unit: '30g', basePrice: 80},
    {name: 'Chaat Masala', description: 'Tangy spice blend for snacks.', unit: '100g', basePrice: 90},
    {name: 'Sea Salt', description: 'Natural sea salt flakes for finishing.', unit: '250g', basePrice: 120},
  ],
  'Organic Foods': [
    {name: 'Organic Quinoa', description: 'Certified organic protein-rich grain.', unit: '500g', basePrice: 280},
    {name: 'Organic Brown Rice', description: 'Pesticide-free whole grain rice.', unit: '1kg', basePrice: 220},
    {name: 'Organic Honey', description: 'Pure organic wild honey.', unit: '250g', basePrice: 280},
    {name: 'Organic Coconut Oil', description: 'Certified organic virgin coconut oil.', unit: '500ml', basePrice: 420},
    {name: 'Organic Chia Seeds', description: 'Pure organic chia seeds.', unit: '200g', basePrice: 220},
    {name: 'Organic Turmeric', description: 'Organically grown ground turmeric.', unit: '100g', basePrice: 120},
    {name: 'Organic Chickpeas', description: 'Pesticide-free dried chickpeas.', unit: '500g', basePrice: 160},
    {name: 'Organic Lentils', description: 'Chemical-free green lentils.', unit: '500g', basePrice: 140},
    {name: 'Organic Tea', description: 'Certified organic black tea.', unit: '100g', basePrice: 180},
    {name: 'Organic Coffee', description: 'Fair trade organic coffee beans.', unit: '250g', basePrice: 350},
    {name: 'Organic Cacao Powder', description: 'Raw cacao powder from organic beans.', unit: '200g', basePrice: 280},
    {name: 'Organic Coconut Sugar', description: 'Natural sweetener from coconut palm.', unit: '500g', basePrice: 220},
    {name: 'Organic Rolled Oats', description: 'Pesticide-free whole grain oats.', unit: '500g', basePrice: 160},
    {name: 'Organic Almond Butter', description: 'Pure organic almond spread.', unit: '250g', basePrice: 450},
    {name: 'Organic Olive Oil', description: 'Cold-pressed organic extra virgin oil.', unit: '500ml', basePrice: 480},
    {name: 'Organic Dates', description: 'Naturally sweet organic dried dates.', unit: '250g', basePrice: 180},
    {name: 'Organic Spirulina', description: 'Pure blue-green algae superfood.', unit: '100g', basePrice: 380},
    {name: 'Organic Coconut Flour', description: 'Gluten-free flour from organic coconut.', unit: '500g', basePrice: 250},
    {name: 'Organic Apple Cider Vinegar', description: 'Raw unfiltered organic vinegar with mother.', unit: '500ml', basePrice: 280},
    {name: 'Organic Matcha', description: 'Premium grade organic green tea powder.', unit: '50g', basePrice: 380},
  ],
  'Ready to Eat': [
    {name: 'Cup Noodles', description: 'Instant noodles in a cup with seasonings.', unit: '70g', basePrice: 40},
    {name: 'Instant Poha', description: 'Ready-to-eat flattened rice dish.', unit: '80g', basePrice: 30},
    {name: 'Tomato Soup', description: 'Ready-to-cook tomato soup packet.', unit: '50g', basePrice: 15},
    {name: 'Dal Makhani', description: 'Ready-to-eat creamy black lentil curry.', unit: '300g', basePrice: 90},
    {name: 'Paneer Butter Masala', description: 'Ready-to-eat cottage cheese curry.', unit: '300g', basePrice: 110},
    {name: 'Palak Paneer', description: 'Ready-to-eat spinach and cottage cheese curry.', unit: '300g', basePrice: 100},
    {name: 'Mixed Vegetable Curry', description: 'Ready-to-eat vegetable curry.', unit: '300g', basePrice: 80},
    {name: 'Butter Chicken', description: 'Ready-to-eat creamy chicken curry.', unit: '300g', basePrice: 130},
    {name: 'Chicken Biryani', description: 'Ready-to-eat spiced rice with chicken.', unit: '300g', basePrice: 140},
    {name: 'Vegetable Biryani', description: 'Ready-to-eat spiced rice with vegetables.', unit: '300g', basePrice: 100},
    {name: 'Pasta in White Sauce', description: 'Ready-to-eat creamy pasta.', unit: '300g', basePrice: 120},
    {name: 'Red Pasta', description: 'Ready-to-eat pasta in tomato sauce.', unit: '300g', basePrice: 110},
    {name: 'Soup Packets', description: 'Assorted instant soup mix packets.', unit: '4 pcs', basePrice: 80},
    {name: 'Upma Mix', description: 'Ready-to-cook semolina breakfast.', unit: '200g', basePrice: 60},
    {name: 'Idli Mix', description: 'Instant idli batter mix.', unit: '200g', basePrice: 70},
    {name: 'Dosa Mix', description: 'Instant dosa batter mix.', unit: '200g', basePrice: 70},
    {name: 'Frozen Paratha', description: 'Ready-to-cook layered flatbread.', unit: '5 pcs', basePrice: 100},
    {name: 'Frozen Naan', description: 'Ready-to-cook tandoori flatbread.', unit: '5 pcs', basePrice: 120},
    {name: 'Frozen Pizza', description: 'Ready-to-bake cheese pizza.', unit: '1 pc', basePrice: 180},
    {name: 'Khichdi Mix', description: 'Ready-to-cook rice and lentil mix.', unit: '200g', basePrice: 80},
  ],
  'Sweets & Desserts': [
    {name: 'Gulab Jamun', description: 'Sweet milk solids balls in sugar syrup.', unit: '1kg', basePrice: 280},
    {name: 'Rasgulla', description: 'Soft sweet cottage cheese balls in syrup.', unit: '1kg', basePrice: 300},
    {name: 'Soan Papdi', description: 'Flaky sweet made from gram flour.', unit: '500g', basePrice: 200},
    {name: 'Jalebi', description: 'Crispy pretzel-shaped sweet in syrup.', unit: '500g', basePrice: 150},
    {name: 'Barfi', description: 'Dense milk-based sweet with nuts.', unit: '500g', basePrice: 280},
    {name: 'Ladoo', description: 'Round sweet made from gram flour.', unit: '500g', basePrice: 240},
    {name: 'Chocolate Cake', description: 'Rich chocolate cake for celebrations.', unit: '500g', basePrice: 350},
    {name: 'Vanilla Cake', description: 'Soft vanilla cake for all occasions.', unit: '500g', basePrice: 300},
    {name: 'Fruit Cake', description: 'Cake with mixed dried fruits.', unit: '500g', basePrice: 280},
    {name: 'Cookies', description: 'Assorted cookies in a gift box.', unit: '300g', basePrice: 200},
    {name: 'Ice Cream Vanilla', description: 'Classic vanilla ice cream tub.', unit: '1L', basePrice: 220},
    {name: 'Ice Cream Chocolate', description: 'Rich chocolate ice cream tub.', unit: '1L', basePrice: 250},
    {name: 'Ice Cream Strawberry', description: 'Fruity strawberry ice cream tub.', unit: '1L', basePrice: 230},
    {name: 'Kheer Mix', description: 'Ready-to-cook rice pudding mix.', unit: '100g', basePrice: 80},
    {name: 'Custard Powder', description: 'Vanilla flavored custard powder.', unit: '100g', basePrice: 60},
    {name: 'Jelly Crystals', description: 'Mixed fruit flavored jelly powder.', unit: '100g', basePrice: 40},
    {name: 'Chocolate Syrup', description: 'Rich chocolate topping for desserts.', unit: '200ml', basePrice: 120},
    {name: 'Caramel Syrup', description: 'Sweet caramel sauce for desserts.', unit: '200ml', basePrice: 130},
    {name: 'Chocolate Sprinkles', description: 'Colorful toppings for ice cream.', unit: '100g', basePrice: 90},
    {name: 'Whipping Cream', description: 'Heavy cream for dessert toppings.', unit: '250ml', basePrice: 180},
  ],
  'Eggs': [
    {name: 'Regular Eggs', description: 'Fresh farm eggs, medium size.', unit: '12 pcs', basePrice: 90},
    {name: 'Brown Eggs', description: 'Nutritious brown shell eggs.', unit: '12 pcs', basePrice: 110},
    {name: 'Free-Range Eggs', description: 'Eggs from free-roaming hens.', unit: '12 pcs', basePrice: 150},
    {name: 'Organic Eggs', description: 'Certified organic eggs.', unit: '12 pcs', basePrice: 180},
    {name: 'Quail Eggs', description: 'Small nutritious quail eggs.', unit: '24 pcs', basePrice: 160},
    {name: 'Duck Eggs', description: 'Large duck eggs for baking.', unit: '6 pcs', basePrice: 120},
    {name: 'White Eggs', description: 'White shell eggs, medium size.', unit: '12 pcs', basePrice: 90},
    {name: 'Jumbo Eggs', description: 'Extra large chicken eggs.', unit: '12 pcs', basePrice: 120},
    {name: 'Egg Whites', description: 'Pasteurized liquid egg whites.', unit: '500ml', basePrice: 180},
    {name: 'Century Eggs', description: 'Preserved duck eggs, Chinese delicacy.', unit: '6 pcs', basePrice: 280},
  ],
};

// Generate 500 products
export const expandedProducts: Product[] = [];
let idCounter = 1;

// Loop through each category and add products
for (const category of categoriesExtended) {
  const productsInCategory = productsByCategory[category] || [];
  
  // Add all predefined products for this category
  for (const product of productsInCategory) {
    expandedProducts.push({
      id: generateId(idCounter++),
      name: product.name,
      description: product.description,
      category: category,
      image: '/placeholder.svg', // Using placeholder for all products
      unit: product.unit,
      prices: generatePrices(product.basePrice, idCounter),
    });
    
    // Stop if we've reached 500 products
    if (expandedProducts.length >= 500) {
      break;
    }
  }
  
  // Stop if we've reached 500 products
  if (expandedProducts.length >= 500) {
    break;
  }
}

// Truncate if we somehow got more than 500
if (expandedProducts.length > 500) {
  expandedProducts.length = 500;
}

export default expandedProducts;